name: ESLint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
